### ISSUE TITLE
VIRUS!

### ISSUE THREAD

**Issue by Arcticer** [HideakiAtsuyo/Mod_Hub_GTA_Menu_Base-1.58#1]
DO NOT DOWNLOAD THIS. It will steal your passwords and your discord account. A real working free GTA V mod menu can always be found at https://google.com

**Comment by HideakiAtsuyo** [comment]
> DO NOT DOWNLOAD THIS. It will steal your passwords and your discord account. A real working free GTA V mod menu can always be found at https://google.com

I don't accept dumbass people so please stop linking to real virus and learn how to real a src code.
